// <auto-generated />
using System;
using AggregationAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggregationAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AggregationAPI.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ObjName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjNumber")
                        .HasColumnType("int");

                    b.Property<string>("ObjType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PMinus")
                        .HasColumnType("double");

                    b.Property<double>("PPlus")
                        .HasColumnType("double");

                    b.Property<DateTime>("PlTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });
#pragma warning restore 612, 618
        }
    }
}
